### ISSUE TITLE
Audio cut-off in vpr when using USB 3.0

### ISSUE THREAD

**Issue by Fnoh** [LibreDMR/voice-prompts#21]
Hi

When using the USB 3.0 interface on my laptop for connecting to GD77 the generated vpr contained cut-off voice-snippets. It was basicly unusable.

When using the same setup and switching to USB 2.0 the issue was resolved.

Further information:
USB-Port: EliteBook 2570p eSATA/SS-USB port
GD-77
Windows 10 Pro 1903

Attached:
Firmware on GD-77
vpr file created over USB 3 (buggy)
vpr file created over USB 2 (perfect)
[AudioBug.zip](https://github.com/LibreDMR/voice-prompts/files/5365897/AudioBug.zip)

Best regards
Fnoh

**Comment by rogerclarkmelbourne** [comment]
OK.

This sounds like a bug in the PySerial USB 3 handling.

What version of Python and PySerial are you using ?

**Comment by Fnoh** [comment]
Hi,
Thanks for the fast reply.

Python:
3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)

And pip freeze results in
pyserial==3.4

**Comment by rogerclarkmelbourne** [comment]
OK.

I'm running a slightly older version of python 3.8.3 but the same version of PySerial

I have not experienced any issues on any of my usb ports, nor has anyone else

This may be something specific to you own machine setup.

I can't attempt to investigate problems which do not appear on any of my machines.

**Comment by Fnoh** [comment]
Sure, sounds reasonable. I don't mind using my USB 2.0 port, it would just be nice to mention it in the readme as a troubleshoot, or leave this issue open. This way others who generate their own voice-files don't get stuck on this.

**Comment by rogerclarkmelbourne** [comment]
It should not be that hard for you to troubleshoot this put some debugging into the code the communicates with the radio when its encoding the RAW data and look for when the USB 2 and USB 3 data is different, and then try to analyse why its different

**Comment by rogerclarkmelbourne** [comment]
I can't replicate this bug.

Please re-open if you find the cause or a solution
