### ISSUE TITLE
Error building english_UK

### ISSUE THREAD

**Issue by sm7tix** [LibreDMR/voice-prompts#47]
I tried to build english_UK. It was my first attempt and it failed.
FileNotFoundError: [Errno 2] No such file or directory: 'Matthew/on.raw'
An error occured while building language "english_UK".
73 de SM7TIX

**Comment by rogerclarkmelbourne** [comment]
One of the external / online , Text To Speech services is (www.voicepolly.pro) is not functioning, and that site was required to perform TTS on any words which needed additional adjustment, specifically "Emphasis" 

I've updated the wordlists to remove any use of the Emphasis functionality.

This will result in the word "On" not being as good as it was before, but there is no other workaround, 

AFIK. There are no other, free, online services that can perform TTS.

You could re-write the script to directly integrate to Amazon Web Services directly, but this would not be useful for most people as it requires a AWS account and private API key and also costs money to use the service directly

**Comment by sm7tix** [comment]
Ok
Med vänlig hälsning

Stefan Rydberg


Den 13 februari 2021 22:15:28 skrev Roger Clark <notifications@github.com>:
